dist: xenial
language: python

addons:
  apt_packages:
    - nodejs
    - npm
    - redis-server
    
python:
    - 3.7
sudo: required
services:
    - docker
script: 
    - pip install node
#    - pip install docker-ce
    - pip install docker-compose
#    - npm install -g npx
    - yarn install # yarn start
#    - npx @0x/launch-kit-wizard && 
#    - docker-compose up
    - docker-machine -v
